services:
  api: 
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SESSION_SECRET=${SESSION_SECRET}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - postgres
    ports:
      - "${HTTP_PORT}:3000"
  postgres:
    image: postgres:16.3
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis-sessions:
    image: redis
    restart: on-failure
    hostname: redis-sessions
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: redis-server --save "" --appendonly no --maxclients 20000
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
volumes:
  postgres:
  redis_data: